prepare:
  description: Prepare Iris data set for training

train:
  description: Train SVC on a particular CV fold
  flags-import: [k, fold]
  requires:
    - operation: prepare
      target-type: link

summarize:
  description:
    Summarize multiple train operations

    Note this is a simulated summary that relies on runs.json. Future
    versions of Guild will support generating runs.json as a dependency.

  # Example of a possible spelling of runs data dependency:

  # requires:
  #   - runs-data: scalars
  #     select: train
  #     name: runs.json
  #     link-runs: no

pipeline:
  steps:
    - prepare
    - train k=5 fold=[1,2,3,4,5]
    - summarize
  delete-on-success: yes
