prepare:
  main: op
  flags-import: all
  tags: [my.guild.ai-998]

train:
  main: op
  flags-import: all
  tags: [my.guild.ai-998]

pipeline:
  tags: [my.guild.ai-998]
  steps:
    - prepare
    - train
